"""add_edge_handles

Revision ID: 1439949b74ad
Revises: 82e10e9b2e3f
Create Date: 2026-01-15 00:35:02.679516

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1439949b74ad'
down_revision = '82e10e9b2e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_edges', sa.Column('source_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('workflow_edges', sa.Column('target_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_edges', 'target_handle')
    op.drop_column('workflow_edges', 'source_handle')
    # ### end Alembic commands ###
