"""Add spec column to WorkflowNode and remove config

Revision ID: 82e10e9b2e3f
Revises: ceedbe88ef0d
Create Date: 2025-12-22 16:16:07.112539

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '82e10e9b2e3f'
down_revision = 'ceedbe88ef0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_nodes', sa.Column('spec', sa.JSON(), nullable=True))
    # Fill existing rows with empty dict if they exist
    op.execute("UPDATE workflow_nodes SET spec = '{}'")
    op.alter_column('workflow_nodes', 'spec', nullable=False)
    op.drop_column('workflow_nodes', 'config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_nodes', sa.Column('config', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workflow_nodes', 'spec')
    # ### end Alembic commands ###
