"""Add V2 config columns to Workflow

Revision ID: ceedbe88ef0d
Revises: dd21742ef7b0
Create Date: 2025-12-21 22:21:03.238288

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ceedbe88ef0d'
down_revision = 'dd21742ef7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('execution_config', sa.JSON(), nullable=False))
    op.add_column('workflow', sa.Column('observability_config', sa.JSON(), nullable=False))
    op.add_column('workflow', sa.Column('ai_metadata', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'ai_metadata')
    op.drop_column('workflow', 'observability_config')
    op.drop_column('workflow', 'execution_config')
    # ### end Alembic commands ###
