"""add_raw_content_to_kbdocument

Revision ID: a89caf9c6db4
Revises: c1dc1e8272fa
Create Date: 2026-05-22 16:21:10.815747

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a89caf9c6db4'
down_revision: Union[str, None] = 'c1dc1e8272fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kbdocument', sa.Column('raw_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kbdocument', 'raw_content')
    # ### end Alembic commands ###
