import type { NodeDefinition } from '../../types'

export const AgentDefinition: NodeDefinition = {
  type: 'action.agent',
  name: 'Agent',
  category: 'ai',
  description: 'Run an AI agent with provider selection, tools, memory, and structured output.',
  icon: 'Bot',
  color: '#8b5cf6',
  inputs: 1,
  outputs: 1,
  properties: [
    {
      name: 'provider',
      label: 'Provider',
      type: 'string',
      default: 'openai',
      required: true,
      placeholder: 'Type or select an AI provider',
      loadOptions: '/ai/providers',
    },
    {
      name: 'credential',
      label: 'Provider Credential',
      type: 'credential',
      required: true,
      dependsOn: ['provider'],
      credentialTypeByField: {
        field: 'provider',
        values: {
          openai: 'openai_api_key',
          anthropic: 'anthropic_api_key',
          google: 'google_api_key',
          groq: 'groq_api_key',
          openrouter: 'openrouter_api_key',
          deepseek: 'deepseek_api_key',
          mistral: 'mistral_api_key',
          xai: 'xai_api_key',
          together: 'together_api_key',
          fireworks: 'fireworks_api_key',
        },
      },
    },
    {
      name: 'model',
      label: 'Model',
      type: 'string',
      required: true,
      placeholder: 'Type or select a model ID',
      loadOptions: '/ai/models',
      loadOptionsDependsOn: [
        'provider',
        'credential',
        'openaiCredential',
        'anthropicCredential',
        'googleCredential',
        'groqCredential',
      ],
    },
    {
      name: 'messages',
      label: 'Messages',
      type: 'json',
      required: true,
      default: [
        { role: 'system', content: 'You are a helpful workflow agent.' },
        { role: 'user', content: '{{trigger.output}}' },
      ],
      description: 'Array of messages with role and content.',
    },
    {
      name: 'tools',
      label: 'Tools',
      type: 'json',
      default: [],
      description: 'Function tools: [{ name, description, parameters }].',
    },
    {
      name: 'toolChoice',
      label: 'Tool Choice',
      type: 'options',
      default: 'auto',
      options: [
        { label: 'Auto', value: 'auto' },
        { label: 'Required', value: 'required' },
        { label: 'None', value: 'none' },
      ],
    },
    {
      name: 'memoryType',
      label: 'Memory',
      type: 'options',
      default: 'none',
      options: [
        { label: 'None', value: 'none' },
        { label: 'Workflow', value: 'workflow' },
      ],
    },
    {
      name: 'memoryKey',
      label: 'Memory Key',
      type: 'string',
      placeholder: 'customer-123',
      condition: { field: 'memoryType', value: 'workflow' },
    },
    {
      name: 'memoryLimit',
      label: 'Memory Limit',
      type: 'number',
      default: 10,
      condition: { field: 'memoryType', value: 'workflow' },
    },
    { name: 'temperature', label: 'Temperature', type: 'number', default: 0.3 },
    { name: 'maxTokens', label: 'Max Output Tokens', type: 'number', default: 4096 },
    {
      name: 'responseFormat',
      label: 'Response Format',
      type: 'json',
      required: false,
      description: 'Optional JSON Schema or provider response-format object.',
    },
    { name: 'timeout', label: 'Timeout (ms)', type: 'number', default: 60000 },
  ],
  outputsSchema: [
    { label: 'content', type: 'string' },
    { label: 'provider', type: 'string' },
    { label: 'model', type: 'string' },
    { label: 'tokens', type: 'object' },
    { label: 'toolCalls', type: 'array' },
    { label: 'structured', type: 'object' },
    { label: 'memory', type: 'array' },
    { label: 'raw', type: 'object' },
  ],
  allowError: true,
}
